#pragma once

#include "Common.h"
#include "ControllableObject.h"

enum SpriteIndexMarioV2
{
	SPRIDX_MARIO_STAND = 0,
	SPRIDX_MARIO_WALK1,
	SPRIDX_MARIO_WALK2,
	SPRIDX_MARIO_WALK3,
	SPRIDX_MARIO_BREAK,
	SPRIDX_MARIO_JUMP,
	SPRIDX_MARIO_SIT,
	SPRIDX_MARIO_CLIMB1,
	SPRIDX_MARIO_CLIMB2,
	SPRIDX_MARIO_SWIM1,
	SPRIDX_MARIO_SWIM2,
	SPRIDX_MARIO_SWIM3,
	SPRIDX_MARIO_SWIM4,
	SPRIDX_MARIO_SWIM5,
	SPRIDX_MARIO_SWIM6,
	SPRIDX_MARIO_RUN1,
	SPRIDX_MARIO_RUN2,
	SPRIDX_MARIO_RUN3,
	SPRIDX_MARIO_HOLDRUN1,
	SPRIDX_MARIO_HOLDRUN2,
	SPRIDX_MARIO_HOLDRUN3,
	SPRIDX_MARIO_HOLDRUN4,
	SPRIDX_MARIO_DRILJUMP1,
	SPRIDX_MARIO_DRILJUMP2,
	SPRIDX_MARIO_DRILJUMP3,
	SPRIDX_MARIO_DRILJUMP4,
	SPRIDX_MARIO_VICTORY,
	SPRIDX_MARIO_HEAD,
	SPRIDX_MARIO_COMMON_LAST = SPRIDX_MARIO_HEAD,

	// Small Mario
	SPRIDX_MARIO_DIE = SPRIDX_MARIO_COMMON_LAST + 1,

	// Big Mario
	SPRIDX_MARIO_MEDIUM = SPRIDX_MARIO_COMMON_LAST + 1,
	SPRIDX_MARIO_TO_GIANT1,
	SPRIDX_MARIO_TO_GIANT2,
	SPRIDX_MARIO_TO_GIANT3,

	// Fire Mario
	SPRIDX_MARIO_THROWFIRE = SPRIDX_MARIO_COMMON_LAST + 1,

	// Shell Mario
	SPRIDX_MARIO_SHELLSLIDE = SPRIDX_MARIO_COMMON_LAST + 1,
	SPRIDX_MARIO_SHELLRUN1,
	SPRIDX_MARIO_SHELLRUN2,
	SPRIDX_MARIO_SHELLRUN3,
};

/*
enum SpriteIndexMarioOld
{
	SPRIDX_MARIO_DIE = 0,
	SPRIDX_MARIO_STAND, // 1
	SPRIDX_MARIO_WALK1,
	SPRIDX_MARIO_WALK2,
	SPRIDX_MARIO_WALK3,
	SPRIDX_MARIO_BREAK,
	SPRIDX_MARIO_JUMP,
	SPRIDX_MARIO_SIT,
	SPRIDX_MARIO_CLIMB1,
	SPRIDX_MARIO_CLIMB2,
	SPRIDX_MARIO_SWIM1,
	SPRIDX_MARIO_SWIM2,
	SPRIDX_MARIO_SWIM3,
	SPRIDX_MARIO_SWIM4,
	SPRIDX_MARIO_SWIM5,
	SPRIDX_MARIO_SWIM6,
	SPRIDX_MARIO_RUN1,
	SPRIDX_MARIO_RUN2,
	SPRIDX_MARIO_RUN3,
	SPRIDX_MARIO_HOLDRUN1,
	SPRIDX_MARIO_HOLDRUN2,
	SPRIDX_MARIO_HOLDRUN3,
	SPRIDX_MARIO_HOLDRUN4,
	SPRIDX_MARIO_DRILJUMP1,
	SPRIDX_MARIO_DRILJUMP2,
	SPRIDX_MARIO_DRILJUMP3,
	SPRIDX_MARIO_DRILJUMP4,
	SPRIDX_MARIO_VICTORY,
	SPRIDX_MARIO_HEAD,

	SPRIDX_MARIO_MEDIUM,

	SPRIDX_MARIO_BIG_STAND, // 29
	SPRIDX_MARIO_BIG_WALK1,
	SPRIDX_MARIO_BIG_WALK2,
	SPRIDX_MARIO_BIG_WALK3,
	SPRIDX_MARIO_BIG_BREAK,
	SPRIDX_MARIO_BIG_JUMP,
	SPRIDX_MARIO_BIG_SIT,
	SPRIDX_MARIO_BIG_CLIMB1,
	SPRIDX_MARIO_BIG_CLIMB2,
	SPRIDX_MARIO_BIG_SWIM1,
	SPRIDX_MARIO_BIG_SWIM2,
	SPRIDX_MARIO_BIG_SWIM3,
	SPRIDX_MARIO_BIG_SWIM4,
	SPRIDX_MARIO_BIG_SWIM5,
	SPRIDX_MARIO_BIG_SWIM6,
	SPRIDX_MARIO_BIG_RUN1,
	SPRIDX_MARIO_BIG_RUN2,
	SPRIDX_MARIO_BIG_RUN3,
	SPRIDX_MARIO_BIG_HOLDRUN1,
	SPRIDX_MARIO_BIG_HOLDRUN2,
	SPRIDX_MARIO_BIG_HOLDRUN3,
	SPRIDX_MARIO_BIG_HOLDRUN4,
	SPRIDX_MARIO_BIG_DRILJUMP1,
	SPRIDX_MARIO_BIG_DRILJUMP2,
	SPRIDX_MARIO_BIG_DRILJUMP3,
	SPRIDX_MARIO_BIG_DRILJUMP4,
	SPRIDX_MARIO_BIG_VICTORY,
	SPRIDX_MARIO_BIG_HEAD,

	SPRIDX_MARIO_SHELL_STAND, // 56
	SPRIDX_MARIO_SHELL_WALK1,
	SPRIDX_MARIO_SHELL_WALK2,
	SPRIDX_MARIO_SHELL_WALK3,
	SPRIDX_MARIO_SHELL_BREAK,
	SPRIDX_MARIO_SHELL_JUMP,
	SPRIDX_MARIO_SHELL_SIT,
	SPRIDX_MARIO_SHELL_CLIMB1,
	SPRIDX_MARIO_SHELL_CLIMB2,
	SPRIDX_MARIO_SHELL_SWIM1,
	SPRIDX_MARIO_SHELL_SWIM2,
	SPRIDX_MARIO_SHELL_SWIM3,
	SPRIDX_MARIO_SHELL_SWIM4,
	SPRIDX_MARIO_SHELL_SWIM5,
	SPRIDX_MARIO_SHELL_SWIM6,
	SPRIDX_MARIO_SHELL_RUN1,
	SPRIDX_MARIO_SHELL_RUN2,
	SPRIDX_MARIO_SHELL_RUN3,
	SPRIDX_MARIO_SHELL_HOLDRUN1,
	SPRIDX_MARIO_SHELL_HOLDRUN2,
	SPRIDX_MARIO_SHELL_HOLDRUN3,
	SPRIDX_MARIO_SHELL_HOLDRUN4,
	SPRIDX_MARIO_SHELL_DRILJUMP1,
	SPRIDX_MARIO_SHELL_DRILJUMP2,
	SPRIDX_MARIO_SHELL_DRILJUMP3,
	SPRIDX_MARIO_SHELL_DRILJUMP4,
	SPRIDX_MARIO_SHELL_VICTORY,
	SPRIDX_MARIO_SHELL_HEAD,

	// Special action sprite
	SPRIDX_MARIO_BIG_THROWFIRE,
	
	SPRIDX_MARIO_TO_GIANT1,
	SPRIDX_MARIO_TO_GIANT2,
	SPRIDX_MARIO_TO_GIANT3,

	SPRIDX_MARIO_SHELL_SLIDE,
	SPRIDX_MARIO_SHELL_SPIN1,
	SPRIDX_MARIO_SHELL_SPIN2,
	SPRIDX_MARIO_SHELL_SPIN3,
	SPRIDX_MARIO_SHELL_SPIN4,

	SPRIDX_MARIO_GIANT_STAND,
	SPRIDX_MARIO_GIANT_WALK1,
	SPRIDX_MARIO_GIANT_WALK2,
	SPRIDX_MARIO_GIANT_WALK3,
	SPRIDX_MARIO_GIANT_JUMP,

	SPRIDX_MARIO_
};
*/

enum SpriteIndexAltVersionMario
{
	SPRIDX_ALTMARIO_DIE = 0,
	SPRIDX_ALTMARIO_STAND, 
	SPRIDX_ALTMARIO_WALK1,
	SPRIDX_ALTMARIO_WALK2,
	SPRIDX_ALTMARIO_WALK3,
	SPRIDX_ALTMARIO_BREAK,
	SPRIDX_ALTMARIO_JUMP,
	SPRIDX_ALTMARIO_SIT,
	SPRIDX_ALTMARIO_CLIMB1,
	SPRIDX_ALTMARIO_CLIMB2,
	SPRIDX_ALTMARIO_SWIM1,
	SPRIDX_ALTMARIO_SWIM2,
	SPRIDX_ALTMARIO_SWIM3,
	SPRIDX_ALTMARIO_SWIM4,
	SPRIDX_ALTMARIO_SWIM5,
	SPRIDX_ALTMARIO_SWIM6,
	SPRIDX_ALTMARIO_RUN1,
	SPRIDX_ALTMARIO_RUN2,
	SPRIDX_ALTMARIO_RUN3,
	SPRIDX_ALTMARIO_HOLDRUN1,
	SPRIDX_ALTMARIO_HOLDRUN2,
	SPRIDX_ALTMARIO_HOLDRUN3,
	SPRIDX_ALTMARIO_HOLDRUN4,
	SPRIDX_ALTMARIO_DRILJUMP1,
	SPRIDX_ALTMARIO_DRILJUMP2,
	SPRIDX_ALTMARIO_DRILJUMP3,
	SPRIDX_ALTMARIO_DRILJUMP4,
	SPRIDX_ALTMARIO_VICTORY,
	SPRIDX_ALTMARIO_HEAD,

	SPRIDX_ALTMARIO_MEDIUM,

	SPRIDX_ALTMARIO_BIG_STAND, 
	SPRIDX_ALTMARIO_BIG_WALK1,
	SPRIDX_ALTMARIO_BIG_WALK2,
	SPRIDX_ALTMARIO_BIG_WALK3,
	SPRIDX_ALTMARIO_BIG_BREAK,
	SPRIDX_ALTMARIO_BIG_JUMP,
	SPRIDX_ALTMARIO_BIG_SIT,
	SPRIDX_ALTMARIO_BIG_CLIMB1,
	SPRIDX_ALTMARIO_BIG_CLIMB2,
	SPRIDX_ALTMARIO_BIG_SWIM1,
	SPRIDX_ALTMARIO_BIG_SWIM2,
	SPRIDX_ALTMARIO_BIG_SWIM3,
	SPRIDX_ALTMARIO_BIG_SWIM4,
	SPRIDX_ALTMARIO_BIG_SWIM5,
	SPRIDX_ALTMARIO_BIG_SWIM6,
	SPRIDX_ALTMARIO_BIG_RUN1,
	SPRIDX_ALTMARIO_BIG_RUN2,
	SPRIDX_ALTMARIO_BIG_RUN3,
	SPRIDX_ALTMARIO_BIG_HOLDRUN1,
	SPRIDX_ALTMARIO_BIG_HOLDRUN2,
	SPRIDX_ALTMARIO_BIG_HOLDRUN3,
	SPRIDX_ALTMARIO_BIG_HOLDRUN4,
	SPRIDX_ALTMARIO_BIG_DRILJUMP1,
	SPRIDX_ALTMARIO_BIG_DRILJUMP2,
	SPRIDX_ALTMARIO_BIG_DRILJUMP3,
	SPRIDX_ALTMARIO_BIG_DRILJUMP4,
	SPRIDX_ALTMARIO_BIG_VICTORY,
	SPRIDX_ALTMARIO_BIG_HEAD,

	SPRIDX_ALTMARIO_MEDIUM_DUMMY,

	SPRIDX_ALTMARIO_FIRE_STAND,
	SPRIDX_ALTMARIO_FIRE_WALK1,
	SPRIDX_ALTMARIO_FIRE_WALK2,
	SPRIDX_ALTMARIO_FIRE_WALK3,
	SPRIDX_ALTMARIO_FIRE_BREAK,
	SPRIDX_ALTMARIO_FIRE_JUMP,
	SPRIDX_ALTMARIO_FIRE_SIT,
	SPRIDX_ALTMARIO_FIRE_CLIMB1,
	SPRIDX_ALTMARIO_FIRE_CLIMB2,
	SPRIDX_ALTMARIO_FIRE_SWIM1,
	SPRIDX_ALTMARIO_FIRE_SWIM2,
	SPRIDX_ALTMARIO_FIRE_SWIM3,
	SPRIDX_ALTMARIO_FIRE_SWIM4,
	SPRIDX_ALTMARIO_FIRE_SWIM5,
	SPRIDX_ALTMARIO_FIRE_SWIM6,
	SPRIDX_ALTMARIO_FIRE_RUN1,
	SPRIDX_ALTMARIO_FIRE_RUN2,
	SPRIDX_ALTMARIO_FIRE_RUN3,
	SPRIDX_ALTMARIO_FIRE_HOLDRUN1,
	SPRIDX_ALTMARIO_FIRE_HOLDRUN2,
	SPRIDX_ALTMARIO_FIRE_HOLDRUN3,
	SPRIDX_ALTMARIO_FIRE_HOLDRUN4,
	SPRIDX_ALTMARIO_FIRE_DRILJUMP1,
	SPRIDX_ALTMARIO_FIRE_DRILJUMP2,
	SPRIDX_ALTMARIO_FIRE_DRILJUMP3,
	SPRIDX_ALTMARIO_FIRE_DRILJUMP4,
	SPRIDX_ALTMARIO_FIRE_VICTORY,
	SPRIDX_ALTMARIO_FIRE_HEAD,

	SPRIDX_ALTMARIO_SHELL_STAND, 
	SPRIDX_ALTMARIO_SHELL_WALK1,
	SPRIDX_ALTMARIO_SHELL_WALK2,
	SPRIDX_ALTMARIO_SHELL_WALK3,
	SPRIDX_ALTMARIO_SHELL_BREAK,
	SPRIDX_ALTMARIO_SHELL_JUMP,
	SPRIDX_ALTMARIO_SHELL_SIT,
	SPRIDX_ALTMARIO_SHELL_CLIMB1,
	SPRIDX_ALTMARIO_SHELL_CLIMB2,
	SPRIDX_ALTMARIO_SHELL_SWIM1,
	SPRIDX_ALTMARIO_SHELL_SWIM2,
	SPRIDX_ALTMARIO_SHELL_SWIM3,
	SPRIDX_ALTMARIO_SHELL_SWIM4,
	SPRIDX_ALTMARIO_SHELL_SWIM5,
	SPRIDX_ALTMARIO_SHELL_SWIM6,
	SPRIDX_ALTMARIO_SHELL_RUN1,
	SPRIDX_ALTMARIO_SHELL_RUN2,
	SPRIDX_ALTMARIO_SHELL_RUN3,
	SPRIDX_ALTMARIO_SHELL_HOLDRUN1,
	SPRIDX_ALTMARIO_SHELL_HOLDRUN2,
	SPRIDX_ALTMARIO_SHELL_HOLDRUN3,
	SPRIDX_ALTMARIO_SHELL_HOLDRUN4,
	SPRIDX_ALTMARIO_SHELL_DRILJUMP1,
	SPRIDX_ALTMARIO_SHELL_DRILJUMP2,
	SPRIDX_ALTMARIO_SHELL_DRILJUMP3,
	SPRIDX_ALTMARIO_SHELL_DRILJUMP4,
	SPRIDX_ALTMARIO_SHELL_VICTORY,
	SPRIDX_ALTMARIO_SHELL_HEAD,

	// Special action sprite
	SPRIDX_ALTMARIO_BIG_THROWFIRE,

	SPRIDX_ALTMARIO_TO_GIANT1,
	SPRIDX_ALTMARIO_TO_GIANT2,
	SPRIDX_ALTMARIO_TO_GIANT3,

	SPRIDX_ALTMARIO_SHELL_SLIDE,
	SPRIDX_ALTMARIO_SHELL_SPIN1,
	SPRIDX_ALTMARIO_SHELL_SPIN2,
	SPRIDX_ALTMARIO_SHELL_SPIN3,
	SPRIDX_ALTMARIO_SHELL_SPIN4,

	SPRIDX_ALTMARIO_GIANT_STAND,
	SPRIDX_ALTMARIO_GIANT_WALK1,
	SPRIDX_ALTMARIO_GIANT_WALK2,
	SPRIDX_ALTMARIO_GIANT_WALK3,
	SPRIDX_ALTMARIO_GIANT_JUMP,

	SPRIDX_ALTMARIO_
};

enum SpriteIndexMarioCostume
{
	SPRIDX_MARIOCOS_STAND = 0,
	SPRIDX_MARIOCOS_SIT,
	SPRIDX_MARIOCOS_WALK1,
	SPRIDX_MARIOCOS_WALK2,
	SPRIDX_MARIOCOS_WALK3,
	SPRIDX_MARIOCOS_RUN1,
	SPRIDX_MARIOCOS_RUN2,
	SPRIDX_MARIOCOS_RUN3,
	SPRIDX_MARIOCOS_BREAK,
	SPRIDX_MARIOCOS_JUMP,
	SPRIDX_MARIOCOS_FALL,
	SPRIDX_MARIOCOS_SWIM1,
	SPRIDX_MARIOCOS_SWIM2,
	SPRIDX_MARIOCOS_SWIM3,
	SPRIDX_MARIOCOS_SWIM4,
	SPRIDX_MARIOCOS_SWIM5,
	SPRIDX_MARIOCOS_SWIM6,
	SPRIDX_MARIOCOS_CLIMB1,
	SPRIDX_MARIOCOS_CLIMB2,
	SPRIDX_MARIOCOS_FLAGCLIMB1,
	SPRIDX_MARIOCOS_FLAGCLIMB2,
	SPRIDX_MARIOCOS_VICTORY,
	SPRIDX_MARIOCOS_HEAD,
};

class Game;
class Mario : public ControllableObject
{
public:
	Mario(Game *pGame, Stage *pStage);
	virtual ~Mario();

	virtual void RequestSprites(Stage *pStage = nullptr);

	virtual bool IsSitSpriteIndex();

	virtual int GetSpriteIndex();
	int GetMiniSpriteIndex();
	int GetBigSpriteIndex();
	int GetShellSpriteIndex();
	virtual SIZE GetSize();

	virtual int GetColor();

	virtual bool CanSit();

	virtual void Render(int nColor = 0xffffffff, int nZOrder = -1);
	virtual void RenderShapeChange();
	
	bool CheckSkipRender();

	void GetMiniToBigSpriteIndex(Sprite **pSprite, Sprite** pSpriteMask, int *pnIndex, float *pfScaleX, float *pfScaleY);
	void GetBigToMiniSpriteIndex(Sprite **pSprite, Sprite** pSpriteMask, int *pnIndex, float *pfScaleX, float *pfScaleY);
	void GetAnyToGiantSpriteIndex(Sprite **pSprite, Sprite** pSpriteMask, int *pnIndex, float *pfScaleX, float *pfScaleY);

	virtual int GetCostumeSpriteIndex();
	virtual void RenderCostume(int nColor = 0xffffffff, int nZOrder = -1);
	virtual void RenderCostumeShapeChange();

	virtual void GetSprite(Sprite** pSprite, Sprite** pSpriteMask, int nShape = -1);

	int m_nSparklingColor;
};