#define MAJOR_VER			3
#define MINOR_VER			4
#define PATCH_VER			0
#define MAJOR_VER_WSTR		L"3"
#define MINOR_VER_WSTR		L"4"
#define PATCH_VER_WSTR		L"0"
#define _VERSION			MAJOR_VER, MINOR_VER, PATCH_VER, REVISION_NUMBER
#define _VERSION_WSTR		MAJOR_VER_WSTR "." MINOR_VER_WSTR "." PATCH_VER_WSTR "." REVISION_NUMBER_WSTR
#define BUILD_DATETIME_WSTR	L"05/0/219_201507"
#define REVISION_NUMBER		0
#define REVISION_NUMBER_WSTR	L"0"
