#pragma once

enum GameStates
{
	GAMESTATE_DESIGN = 1,
	GAMESTATE_DESIGNPLAY, // Play in tool

	GAMESTATE_INIT,
	GAMESTATE_CREDITS,

	GAMESTATE_LOGO, // Nintendo logo & show licenses
	GAMESTATE_TITLE, // Title Menu
	GAMESTATE_APPUPDATE,
	GAMESTATE_REGISTERUSER,
	GAMESTATE_DEMOPLAY,
	GAMESTATE_STAGEINTRO,

	GAMESTATE_PLAY,
	GAMESTATE_TEST, // Clone of play (DebugMode)

	// Animations
	GAMESTATE_SHAPECHANGE,
	GAMESTATE_DIE,

	GAMESTATE_MESSAGEBLOCK,

	// Auto Moving events
	GAMESTATE_ENTERSTAGE,
	GAMESTATE_ENTERPIPE,
	GAMESTATE_EXITPIPE,
	GAMESTATE_ENTERSKY, // Ground->Sky
	GAMESTATE_SKYINTRO,
	GAMESTATE_ENTERDOOR,
	GAMESTATE_EXITDOOR,

	// Stage Clear Events
	GAMESTATE_FLAGDOWN, // Goal in through flagpole
	GAMESTATE_GOAL, // Reached castle door
	GAMESTATE_CUTBRIDGE,
	GAMESTATE_RESCUEPRINCESS,
	GAMESTATE_HITGOALBOX, 
	GAMESTATE_HITGOALPOST,

	GAMESTATE_TIMEUP,
	GAMESTATE_GAMEOVER,

	// Custom Modes
	GAMESTATE_SINGLESTAGECLEAR,
	GAMESTATE_SINGLESTAGEGAMEOVER,

	GAMESTATE_,
};

namespace GameDefaults
{
	const int nInitialState = GAMESTATE_LOGO;
}
