#pragma once

enum StageThemeSetTypes
{
	STAGETHEMESET_CUSTOM = 0,
	STAGETHEMESET_OVERWORLD,
	STAGETHEMESET_UNDERGROUND,
	STAGETHEMESET_CASTLE,
	STAGETHEMESET_UNDERWATER,

	STAGETHEMESET_GHOSTHOUSE,	// From MarioMaker
	STAGETHEMESET_AIRSHIP,		// From MarioMaker

	STAGETHEMESET_SNOW,

	STAGETHEMESET_,
};

enum StageThemeTypes
{
	STAGETHEME_OVERWORLD = 0,
	STAGETHEME_UNDERGROUND,
	STAGETHEME_CASTLE,
	STAGETHEME_UNDERWATER,
	STAGETHEME_CASTLEUNDERWATER, // Underwater + PurplePipe
	STAGETHEME_CLASSICSNOW, // Overworld + WhitePipe
	STAGETHEME_MUSHROOM, // Overworld + RedPipe
	STAGETHEME_GRAY,

	STAGETHEME_GHOSTHOUSE,	// From MarioMaker
	STAGETHEME_AIRSHIP,		// From MarioMaker

	STAGETHEME_SNOW, // by Jordan Haris
};

enum StageBackgroundThemeTypes
{
	STAGEBGTHEME_MOUNTAIN = 0,
	STAGEBGTHEME_CLOUD,
	STAGEBGTHEME_NONE,
	STAGEBGTHEME_UNDERWATER,
	STAGEBGTHEME_FENCE,
	STAGEBGTHEME_SNOW,
	STAGEBGTHEME_NIGHT,
	STAGEBGTHEME_SNOWNIGHT,
	STAGEBGTHEME_REDCLOUD,

	STAGEBGTHEME_UNDERGROUND,	// From MarioMaker
	STAGEBGTHEME_CASTLE,		// From MarioMaker
	STAGEBGTHEME_GHOSTHOUSE,	// From MarioMaker
	STAGEBGTHEME_AIRSHIP,		// From MarioMaker
};
